export const REGISTER_ACCOUNT = "REGISTER_ACCOUNT";
export const LOGIN = "LOGIN";
export const RECEIVE_TOKEN = "RECEIVE_TOKEN";
export const START_AUTH_REQUEST = "START_AUTH_REQUEST";
export const END_AUTH_REQUEST = "END_AUTH_REQUEST";
